//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSSPReportWriterHelperDLL.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportServiceRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportServiceRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSSPReportWriterHelperDLL.Services.Resources.ReportServiceRes", typeof(ReportServiceRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] does not contain {1} items.
        /// </summary>
        public static string _DoesNotContain_Items {
            get {
                return ResourceManager.GetString("_DoesNotContain_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist for {1}.
        /// </summary>
        public static string _DoesNotExistFor_ {
            get {
                return ResourceManager.GetString("_DoesNotExistFor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not an allowable condition terms {1}.
        /// </summary>
        public static string _IsNotAnAllowableConditionTerms_ {
            get {
                return ResourceManager.GetString("_IsNotAnAllowableConditionTerms_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required for line {1} and item {2}.
        /// </summary>
        public static string _IsRequiredForLine_AndItem_ {
            get {
                return ResourceManager.GetString("_IsRequiredForLine_AndItem_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required in {1}.
        /// </summary>
        public static string _IsRequiredIn_ {
            get {
                return ResourceManager.GetString("_IsRequiredIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required when using {1} for {2} condition.
        /// </summary>
        public static string _IsRequiredWhenUsing_For_Condition {
            get {
                return ResourceManager.GetString("_IsRequiredWhenUsing_For_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not implemented in {1}.
        /// </summary>
        public static string _NotImplementedIn_ {
            get {
                return ResourceManager.GetString("_NotImplementedIn_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of tag {1} does not exist at line {2}.
        /// </summary>
        public static string _OfTag_DoesNotExistAtLine_ {
            get {
                return ResourceManager.GetString("_OfTag_DoesNotExistAtLine_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should end with {1}.
        /// </summary>
        public static string _ShouldEndWith_ {
            get {
                return ResourceManager.GetString("_ShouldEndWith_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] should not be null or empty..
        /// </summary>
        public static string _ShouldNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("_ShouldNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should only have {1} item(s).
        /// </summary>
        public static string _ShouldOnlyHave_Items {
            get {
                return ResourceManager.GetString("_ShouldOnlyHave_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tag does not allow sorting.
        /// </summary>
        public static string _TagDoesNotAllowSorting {
            get {
                return ResourceManager.GetString("_TagDoesNotAllowSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tag must be followed with a return.
        /// </summary>
        public static string _TagMustBeFollowedWithAReturn {
            get {
                return ResourceManager.GetString("_TagMustBeFollowedWithAReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tag should not be within a table.
        /// </summary>
        public static string _TagShouldNotBeWithinATable {
            get {
                return ResourceManager.GetString("_TagShouldNotBeWithinATable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All nodes are smaller than contour value.
        /// </summary>
        public static string AllNodesAreSmallerThanContourValue {
            get {
                return ResourceManager.GetString("AllNodesAreSmallerThanContourValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowable condition terms are {0}.
        /// </summary>
        public static string AllowableConditionTermsAre_ {
            get {
                return ResourceManager.GetString("AllowableConditionTermsAre_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowable document types {0}.
        /// </summary>
        public static string AllowableDocumentTypes_ {
            get {
                return ResourceManager.GetString("AllowableDocumentTypes_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowable filters [{0}].
        /// </summary>
        public static string AllowableFilters_ {
            get {
                return ResourceManager.GetString("AllowableFilters_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowable languages {0}.
        /// </summary>
        public static string AllowableLanguages_ {
            get {
                return ResourceManager.GetString("AllowableLanguages_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowable values {0}.
        /// </summary>
        public static string AllowableValues_ {
            get {
                return ResourceManager.GetString("AllowableValues_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowable values for {0} in {1}.
        /// </summary>
        public static string AllowableValuesFor_In_ {
            get {
                return ResourceManager.GetString("AllowableValuesFor_In_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tags must be within a Start tag.
        /// </summary>
        public static string AllTagsMustBeWithinAStartTag {
            get {
                return ResourceManager.GetString("AllTagsMustBeWithinAStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        public static string Amplitude {
            get {
                return ResourceManager.GetString("Amplitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Decay Factor.
        /// </summary>
        public static string AverageDecayFactor {
            get {
                return ResourceManager.GetString("AverageDecayFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom of layer.
        /// </summary>
        public static string BottomOfLayer {
            get {
                return ResourceManager.GetString("BottomOfLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundary conditions.
        /// </summary>
        public static string BoundaryConditions {
            get {
                return ResourceManager.GetString("BoundaryConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celcius.
        /// </summary>
        public static string Celcius {
            get {
                return ResourceManager.GetString("Celcius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChildTVType is required if ParentTVItemID is not 0.
        /// </summary>
        public static string ChildTVTypeIsRequiredIfParentTVItemIDIsNotZero {
            get {
                return ResourceManager.GetString("ChildTVTypeIsRequiredIfParentTVItemIDIsNotZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition {0} missing value.
        /// </summary>
        public static string Condition_MissingValue {
            get {
                return ResourceManager.GetString("Condition_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition [{0}] not well formed.
        /// </summary>
        public static string Condition_NotWellFormed {
            get {
                return ResourceManager.GetString("Condition_NotWellFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition {0} not well formed. {1} requires {2}.
        /// </summary>
        public static string Condition_NotWellFormed_Requires_ {
            get {
                return ResourceManager.GetString("Condition_NotWellFormed_Requires_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionText missing number after {0}.
        /// </summary>
        public static string ConditionTextMissingNumberAfter_ {
            get {
                return ResourceManager.GetString("ConditionTextMissingNumberAfter_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionText missing second number after {0}.
        /// </summary>
        public static string ConditionTextMissingSecondNumberAfter_ {
            get {
                return ResourceManager.GetString("ConditionTextMissingSecondNumberAfter_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionText missing text after {0}.
        /// </summary>
        public static string ConditionTextMissingTextAfter_ {
            get {
                return ResourceManager.GetString("ConditionTextMissingTextAfter_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition text should not be empty.
        /// </summary>
        public static string ConditionTextShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("ConditionTextShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConditionText should not contain {0}.
        /// </summary>
        public static string ConditionTextShouldNotContain_ {
            get {
                return ResourceManager.GetString("ConditionTextShouldNotContain_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contour value.
        /// </summary>
        public static string ContourValue {
            get {
                return ResourceManager.GetString("ContourValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not clear all rows of Subsector Special Table {0}.
        /// </summary>
        public static string CouldNotClearAllRowsOfSubsectorSpecialTable_ {
            get {
                return ResourceManager.GetString("CouldNotClearAllRowsOfSubsectorSpecialTable_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert to float {0}.
        /// </summary>
        public static string CouldNotConvertToFloat_ {
            get {
                return ResourceManager.GetString("CouldNotConvertToFloat_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0} {1}.
        /// </summary>
        public static string CouldNotFind__ {
            get {
                return ResourceManager.GetString("CouldNotFind__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find [{0}] starting at {1}.
        /// </summary>
        public static string CouldNotFind_StartingAt_ {
            get {
                return ResourceManager.GetString("CouldNotFind_StartingAt_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0} with {1} equal {2}.
        /// </summary>
        public static string CouldNotFind_With_Equal_ {
            get {
                return ResourceManager.GetString("CouldNotFind_With_Equal_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find end tag [{0}] of [{1}].
        /// </summary>
        public static string CouldNotFindEndTag_Of_ {
            get {
                return ResourceManager.GetString("CouldNotFindEndTag_Of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find file {0}.
        /// </summary>
        public static string CouldNotFindFile_ {
            get {
                return ResourceManager.GetString("CouldNotFindFile_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find first line. Returns are required..
        /// </summary>
        public static string CouldNotFindFirstLineReturnsAreRequired {
            get {
                return ResourceManager.GetString("CouldNotFindFirstLineReturnsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find return in tag.
        /// </summary>
        public static string CouldNotFindReturnInTag {
            get {
                return ResourceManager.GetString("CouldNotFindReturnInTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find tag {0}.
        /// </summary>
        public static string CouldNotFindTag_ {
            get {
                return ResourceManager.GetString("CouldNotFindTag_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find tag to remove {0}.
        /// </summary>
        public static string CouldNotFindTagToRemove_ {
            get {
                return ResourceManager.GetString("CouldNotFindTagToRemove_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSVTagText is empty.
        /// </summary>
        public static string CSVTagTextIsEmpty {
            get {
                return ResourceManager.GetString("CSVTagTextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date string not well formed {0}. It should be something like {1}.
        /// </summary>
        public static string DateStringNotWellFormed_ItShouldBeSomethingLike_ {
            get {
                return ResourceManager.GetString("DateStringNotWellFormed_ItShouldBeSomethingLike_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 0.
        /// </summary>
        public static string Day0 {
            get {
                return ResourceManager.GetString("Day0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 1.
        /// </summary>
        public static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 10.
        /// </summary>
        public static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 2.
        /// </summary>
        public static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 3.
        /// </summary>
        public static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 4.
        /// </summary>
        public static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 5.
        /// </summary>
        public static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 6.
        /// </summary>
        public static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 7.
        /// </summary>
        public static string Day7 {
            get {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 8.
        /// </summary>
        public static string Day8 {
            get {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day 9.
        /// </summary>
        public static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        public static string DayLowerCase {
            get {
                return ResourceManager.GetString("DayLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay is constant.
        /// </summary>
        public static string DecayIsConstant {
            get {
                return ResourceManager.GetString("DecayIsConstant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay is variable.
        /// </summary>
        public static string DecayIsVariable {
            get {
                return ResourceManager.GetString("DecayIsVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to degree.
        /// </summary>
        public static string DegreeLowerCase {
            get {
                return ResourceManager.GetString("DegreeLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depths.
        /// </summary>
        public static string Depths {
            get {
                return ResourceManager.GetString("Depths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptiveTag.
        /// </summary>
        public static string DescriptiveTag {
            get {
                return ResourceManager.GetString("DescriptiveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effluent.
        /// </summary>
        public static string Effluent {
            get {
                return ResourceManager.GetString("Effluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element nodes.
        /// </summary>
        public static string ElementNodes {
            get {
                return ResourceManager.GetString("ElementNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element type {0} is not supported.
        /// </summary>
        public static string ElementType_IsNotSupported {
            get {
                return ResourceManager.GetString("ElementType_IsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum [{0}] not found. Should be one of [{1}].
        /// </summary>
        public static string Enum_NotFoundShouldBeOneOf_ {
            get {
                return ResourceManager.GetString("Enum_NotFoundShouldBeOneOf_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example {0}.
        /// </summary>
        public static string Example_ {
            get {
                return ResourceManager.GetString("Example_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC .
        /// </summary>
        public static string FCMPNPer100ML {
            get {
                return ResourceManager.GetString("FCMPNPer100ML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC  at the end.
        /// </summary>
        public static string FCMPNPer100MLEnd {
            get {
                return ResourceManager.GetString("FCMPNPer100MLEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC at the beginning.
        /// </summary>
        public static string FCMPNPer100MLStart {
            get {
                return ResourceManager.GetString("FCMPNPer100MLStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FC MPN Pollution Contour.
        /// </summary>
        public static string FCMPNPollutionContour {
            get {
                return ResourceManager.GetString("FCMPNPollutionContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist [{0}].
        /// </summary>
        public static string FileDoesNotExist_ {
            get {
                return ResourceManager.GetString("FileDoesNotExist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileType.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First item should be Start.
        /// </summary>
        public static string FirstItemShouldBeStart {
            get {
                return ResourceManager.GetString("FirstItemShouldBeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First line of CSV template should not contain {0}.
        /// </summary>
        public static string FirstLineOfCSVTemplateShouldNotContain_ {
            get {
                return ResourceManager.GetString("FirstLineOfCSVTemplateShouldNotContain_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First line of KML template should not contain {0}.
        /// </summary>
        public static string FirstLineOfKMLTemplateShouldNotContain_ {
            get {
                return ResourceManager.GetString("FirstLineOfKMLTemplateShouldNotContain_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First line variable count {0} does not equal result count {1}.
        /// </summary>
        public static string FirstLineVariableCount_DoesNotEqualToResultCount_ {
            get {
                return ResourceManager.GetString("FirstLineVariableCount_DoesNotEqualToResultCount_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First tag in document must be a start tag.
        /// </summary>
        public static string FirstTagInDocumentMustBeAStartTag {
            get {
                return ResourceManager.GetString("FirstTagInDocumentMustBeAStartTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow.
        /// </summary>
        public static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow at the end.
        /// </summary>
        public static string FlowEnd {
            get {
                return ResourceManager.GetString("FlowEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow  at the beginning.
        /// </summary>
        public static string FlowStart {
            get {
                return ResourceManager.GetString("FlowStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr or en.
        /// </summary>
        public static string FrOrEn {
            get {
                return ResourceManager.GetString("FrOrEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetReportType returned null for {0}.
        /// </summary>
        public static string GetReportTypeReturnedNullFor_ {
            get {
                return ResourceManager.GetString("GetReportTypeReturnedNullFor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to included.
        /// </summary>
        public static string IncludedLowerCase {
            get {
                return ResourceManager.GetString("IncludedLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is continuous.
        /// </summary>
        public static string IsContinuous {
            get {
                return ResourceManager.GetString("IsContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not continuous.
        /// </summary>
        public static string IsNotContinuous {
            get {
                return ResourceManager.GetString("IsNotContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name {0} not allowed.
        /// </summary>
        public static string ItemName_NotAllowed {
            get {
                return ResourceManager.GetString("ItemName_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMLTagText is empty.
        /// </summary>
        public static string KMLTagTextIsEmpty {
            get {
                return ResourceManager.GetString("KMLTagTextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language {0} not allowed.
        /// </summary>
        public static string Language_NotAllowed {
            get {
                return ResourceManager.GetString("Language_NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} has {1} parameters. The maximum is {2}.
        /// </summary>
        public static string Line_Has_ParametersTheMaximumIs_ {
            get {
                return ResourceManager.GetString("Line_Has_ParametersTheMaximumIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} item {1} should be a number.
        /// </summary>
        public static string Line_Item_ShouldBeANumber {
            get {
                return ResourceManager.GetString("Line_Item_ShouldBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} item {1} should be one of {2}.
        /// </summary>
        public static string Line_Item_ShouldBeOneOf_ {
            get {
                return ResourceManager.GetString("Line_Item_ShouldBeOneOf_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} should have {1} items.
        /// </summary>
        public static string Line_ShouldHave_Items {
            get {
                return ResourceManager.GetString("Line_ShouldHave_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line {0} should start with {1}.
        /// </summary>
        public static string Line_ShouldStartWith_ {
            get {
                return ResourceManager.GetString("Line_ShouldStartWith_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manning number.
        /// </summary>
        public static string ManningNumber {
            get {
                return ResourceManager.GetString("ManningNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of precipitation days is {0}.
        /// </summary>
        public static string MaximumNumberOfPrecipitationDaysIs_ {
            get {
                return ResourceManager.GetString("MaximumNumberOfPrecipitationDaysIs_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of sigma layer [{0}]..
        /// </summary>
        public static string MaximumNumberOfSigmaLayers_ {
            get {
                return ResourceManager.GetString("MaximumNumberOfSigmaLayers_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE 3 not implemented yet.
        /// </summary>
        public static string MIKE3NotImplementedYet {
            get {
                return ResourceManager.GetString("MIKE3NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE boundary condition code.
        /// </summary>
        public static string MIKEBoundaryConditionCode {
            get {
                return ResourceManager.GetString("MIKEBoundaryConditionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE boundary condition format.
        /// </summary>
        public static string MIKEBoundaryConditionFormat {
            get {
                return ResourceManager.GetString("MIKEBoundaryConditionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE boundary condition length.
        /// </summary>
        public static string MIKEBoundaryConditionLength {
            get {
                return ResourceManager.GetString("MIKEBoundaryConditionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE boundary condition level or velocity.
        /// </summary>
        public static string MIKEBoundaryConditionLevelOrVelocity {
            get {
                return ResourceManager.GetString("MIKEBoundaryConditionLevelOrVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE boundary condition name.
        /// </summary>
        public static string MIKEBoundaryConditionName {
            get {
                return ResourceManager.GetString("MIKEBoundaryConditionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE boundary conditions.
        /// </summary>
        public static string MIKEBoundaryConditions {
            get {
                return ResourceManager.GetString("MIKEBoundaryConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE mesh.
        /// </summary>
        public static string MIKEMesh {
            get {
                return ResourceManager.GetString("MIKEMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE pollution animation.
        /// </summary>
        public static string MIKEPollutionAnimation {
            get {
                return ResourceManager.GetString("MIKEPollutionAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE pollution limit.
        /// </summary>
        public static string MIKEPollutionLimit {
            get {
                return ResourceManager.GetString("MIKEPollutionLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MikeScenario.
        /// </summary>
        public static string MikeScenario {
            get {
                return ResourceManager.GetString("MikeScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MikeScenarioTVItemID.
        /// </summary>
        public static string MikeScenarioTVItemID {
            get {
                return ResourceManager.GetString("MikeScenarioTVItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MikeSource.
        /// </summary>
        public static string MikeSource {
            get {
                return ResourceManager.GetString("MikeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MikeSourceID.
        /// </summary>
        public static string MikeSourceID {
            get {
                return ResourceManager.GetString("MikeSourceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE source name is empty.
        /// </summary>
        public static string MIKESourceNameIsEmpty {
            get {
                return ResourceManager.GetString("MIKESourceNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MikeSourceStartEnd.
        /// </summary>
        public static string MikeSourceStartEnd {
            get {
                return ResourceManager.GetString("MikeSourceStartEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIKE study area.
        /// </summary>
        public static string MIKEStudyArea {
            get {
                return ResourceManager.GetString("MIKEStudyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string MinutesLowerCase {
            get {
                return ResourceManager.GetString("MinutesLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model input.
        /// </summary>
        public static string ModelInput {
            get {
                return ResourceManager.GetString("ModelInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model parameters.
        /// </summary>
        public static string ModelParameters {
            get {
                return ResourceManager.GetString("ModelParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} tag found in document.
        /// </summary>
        public static string No_TagFoundInDocument {
            get {
                return ResourceManager.GetString("No_TagFoundInDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nodes.
        /// </summary>
        public static string Nodes {
            get {
                return ResourceManager.GetString("Nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north clockwise.
        /// </summary>
        public static string NorthClockwiseLowerCase {
            get {
                return ResourceManager.GetString("NorthClockwiseLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tag found in document.
        /// </summary>
        public static string NoTagFoundInDocument {
            get {
                return ResourceManager.GetString("NoTagFoundInDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet..
        /// </summary>
        public static string NotImplementedYet {
            get {
                return ResourceManager.GetString("NotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not included.
        /// </summary>
        public static string NotIncludedLowerCase {
            get {
                return ResourceManager.GetString("NotIncludedLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not used.
        /// </summary>
        public static string NotUsedLowerCase {
            get {
                return ResourceManager.GetString("NotUsedLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Wind.
        /// </summary>
        public static string NoWind {
            get {
                return ResourceManager.GetString("NoWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of web tide nodes.
        /// </summary>
        public static string NumberOfWebTideNodes {
            get {
                return ResourceManager.GetString("NumberOfWebTideNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number without decimal is required after {0}.
        /// </summary>
        public static string NumberWithoutDecimalIsRequiredAfter_ {
            get {
                return ResourceManager.GetString("NumberWithoutDecimalIsRequiredAfter_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Start tag is required.
        /// </summary>
        public static string OneStartTagIsRequired {
            get {
                return ResourceManager.GetString("OneStartTagIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one Start tag is allowed in CSV template.
        /// </summary>
        public static string OnlyOneStartTagIsAllowedInCSVTemplate {
            get {
                return ResourceManager.GetString("OnlyOneStartTagIsAllowedInCSVTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one Start tag is allowed in KML template.
        /// </summary>
        public static string OnlyOneStartTagIsAllowedInKMLTemplate {
            get {
                return ResourceManager.GetString("OnlyOneStartTagIsAllowedInKMLTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to parameter type.
        /// </summary>
        public static string ParameterType {
            get {
                return ResourceManager.GetString("ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param values string not well formed {0}.
        /// </summary>
        public static string ParamValuesStringNotWellFormed_ {
            get {
                return ResourceManager.GetString("ParamValuesStringNotWellFormed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PFS {0} Error {1}.
        /// </summary>
        public static string PFS_Error_ {
            get {
                return ResourceManager.GetString("PFS_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a field.
        /// </summary>
        public static string PleaseSelectAField {
            get {
                return ResourceManager.GetString("PleaseSelectAField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select appropriate starting web page.
        /// </summary>
        public static string PleaseSelectAppropriateStartingWebPage {
            get {
                return ResourceManager.GetString("PleaseSelectAppropriateStartingWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution animation.
        /// </summary>
        public static string PollutionAnimation {
            get {
                return ResourceManager.GetString("PollutionAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution contour.
        /// </summary>
        public static string PollutionContour {
            get {
                return ResourceManager.GetString("PollutionContour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pollution limits.
        /// </summary>
        public static string PollutionLimits {
            get {
                return ResourceManager.GetString("PollutionLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygons.
        /// </summary>
        public static string Polygons {
            get {
                return ResourceManager.GetString("Polygons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSU.
        /// </summary>
        public static string PSU {
            get {
                return ResourceManager.GetString("PSU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain (mm).
        /// </summary>
        public static string Rain_mm {
            get {
                return ResourceManager.GetString("Rain_mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RangeStartTag_Text.
        /// </summary>
        public static string RangeStartTag_Text {
            get {
                return ResourceManager.GetString("RangeStartTag_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RangeStartTag text is empty.
        /// </summary>
        public static string RangeStartTagTextIsEmpty {
            get {
                return ResourceManager.GetString("RangeStartTagTextIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportFieldType is {0}. It has to be one of {1}.
        /// </summary>
        public static string ReportFieldTypeIs_ItHasToBeOneOf_ {
            get {
                return ResourceManager.GetString("ReportFieldTypeIs_ItHasToBeOneOf_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportTreeNodeList.
        /// </summary>
        public static string ReportTreeNodeList {
            get {
                return ResourceManager.GetString("ReportTreeNodeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportType.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Frequency.
        /// </summary>
        public static string ResultFrequency {
            get {
                return ResourceManager.GetString("ResultFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity.
        /// </summary>
        public static string Salinity {
            get {
                return ResourceManager.GetString("Salinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity at the end.
        /// </summary>
        public static string SalinityEnd {
            get {
                return ResourceManager.GetString("SalinityEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salinity  at the beginning.
        /// </summary>
        public static string SalinityStart {
            get {
                return ResourceManager.GetString("SalinityStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario time at the end.
        /// </summary>
        public static string ScenarioEndTime {
            get {
                return ResourceManager.GetString("ScenarioEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario time  at the beginning.
        /// </summary>
        public static string ScenarioStartTime {
            get {
                return ResourceManager.GetString("ScenarioStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source included.
        /// </summary>
        public static string SourceIncluded {
            get {
                return ResourceManager.GetString("SourceIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Not Included.
        /// </summary>
        public static string SourceNotIncluded {
            get {
                return ResourceManager.GetString("SourceNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceNumberString.
        /// </summary>
        public static string SourceNumberString {
            get {
                return ResourceManager.GetString("SourceNumberString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spill.
        /// </summary>
        public static string Spill {
            get {
                return ResourceManager.GetString("Spill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spill Time at the end.
        /// </summary>
        public static string SpillEndTime {
            get {
                return ResourceManager.GetString("SpillEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spill time  at the beginning.
        /// </summary>
        public static string SpillStartTime {
            get {
                return ResourceManager.GetString("SpillStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and end tides.
        /// </summary>
        public static string StartAndEndTides {
            get {
                return ResourceManager.GetString("StartAndEndTides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start or Loop.
        /// </summary>
        public static string StartOrLoop {
            get {
                return ResourceManager.GetString("StartOrLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartPos {0} should be smaller than EndPos {1}.
        /// </summary>
        public static string StartPos_ShouldBeSmallerThanEndPos_ {
            get {
                return ResourceManager.GetString("StartPos_ShouldBeSmallerThanEndPos_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start tag must not reside in a table.
        /// </summary>
        public static string StartTagMustNotResideInATable {
            get {
                return ResourceManager.GetString("StartTagMustNotResideInATable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartText.
        /// </summary>
        public static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub type and letter string not well formed {0}. It should be something like {1}.
        /// </summary>
        public static string SubTypeAndLetterStringNotWellFormed_ItShouldBeSomethingLike_ {
            get {
                return ResourceManager.GetString("SubTypeAndLetterStringNotWellFormed_ItShouldBeSomethingLike_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableType.
        /// </summary>
        public static string TableType {
            get {
                return ResourceManager.GetString("TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} has more than 1 child tag which is not allowed in CSV templates.
        /// </summary>
        public static string Tag_HasMoreThan1ChildTagWhichIsNotAllowedInCSVTemplates {
            get {
                return ResourceManager.GetString("Tag_HasMoreThan1ChildTagWhichIsNotAllowedInCSVTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} has more than 1 child tag which is not allowed in KML templates.
        /// </summary>
        public static string Tag_HasMoreThan1ChildTagWhichIsNotAllowedInKMLTemplates {
            get {
                return ResourceManager.GetString("Tag_HasMoreThan1ChildTagWhichIsNotAllowedInKMLTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag [{0}] not implemented.
        /// </summary>
        public static string Tag_NotImplemented {
            get {
                return ResourceManager.GetString("Tag_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag {0} not well formed. It should have a structure like {1}.
        /// </summary>
        public static string Tag_NotWellFormedItShouldHaveAStructureLike_ {
            get {
                return ResourceManager.GetString("Tag_NotWellFormedItShouldHaveAStructureLike_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagItem.
        /// </summary>
        public static string TagItem {
            get {
                return ResourceManager.GetString("TagItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag name should be Start or Loop.
        /// </summary>
        public static string TagNameShouldBeStartOrLoop {
            get {
                return ResourceManager.GetString("TagNameShouldBeStartOrLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature at the end.
        /// </summary>
        public static string TemperatureEnd {
            get {
                return ResourceManager.GetString("TemperatureEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature  at the beginning.
        /// </summary>
        public static string TemperatureStart {
            get {
                return ResourceManager.GetString("TemperatureStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text between markers is empty.
        /// </summary>
        public static string TextBetweenMarkersIsEmpty {
            get {
                return ResourceManager.GetString("TextBetweenMarkersIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many conditions for {0}.
        /// </summary>
        public static string TooManyConditionsFor_ {
            get {
                return ResourceManager.GetString("TooManyConditionsFor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of layer.
        /// </summary>
        public static string TopOfLayer {
            get {
                return ResourceManager.GetString("TopOfLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVFile.
        /// </summary>
        public static string TVFile {
            get {
                return ResourceManager.GetString("TVFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVItem.
        /// </summary>
        public static string TVItem {
            get {
                return ResourceManager.GetString("TVItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVItemID.
        /// </summary>
        public static string TVItemID {
            get {
                return ResourceManager.GetString("TVItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to used.
        /// </summary>
        public static string UsedLowerCase {
            get {
                return ResourceManager.GetString("UsedLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {0} does not exist for item {1}.
        /// </summary>
        public static string Variable_DoesNotExistForItem_ {
            get {
                return ResourceManager.GetString("Variable_DoesNotExistForItem_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {0} not used within tag.
        /// </summary>
        public static string Variable_NotUseWithinTag {
            get {
                return ResourceManager.GetString("Variable_NotUseWithinTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {0} was not identified and is used within tag.
        /// </summary>
        public static string Variable_WasNotIdentifiedAndIsUsedWithinTag {
            get {
                return ResourceManager.GetString("Variable_WasNotIdentifiedAndIsUsedWithinTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web tide data set.
        /// </summary>
        public static string WebTideDataSet {
            get {
                return ResourceManager.GetString("WebTideDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web tide nodes.
        /// </summary>
        public static string WebTideNodes {
            get {
                return ResourceManager.GetString("WebTideNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind.
        /// </summary>
        public static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Direction.
        /// </summary>
        public static string WindDirection {
            get {
                return ResourceManager.GetString("WindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a tag {0} which is not closed properly.
        /// </summary>
        public static string YouHaveATag_WhichIsNotClosedProperly {
            get {
                return ResourceManager.GetString("YouHaveATag_WhichIsNotClosedProperly", resourceCulture);
            }
        }
    }
}
